Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANLTW.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DOANLTW.Models;
namespace DOANLTW.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        WEBTHUCANNHANHDataContext data = new WEBTHUCANNHANHDataContext();
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, KhachHang kh)
        {
            var hoten = collection["HoTenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["MatKhau"];
            var matkhaunhaplai = collection["MatKhauNhapLai"];
            var diachi = collection["DiaChi"];
            var email = collection["Email"];
            var dienthoai = collection["DienThoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["NgaySinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["loi1"] = "Họ tên khách hàng không được để trống";

            }
            else if (string.IsNullOrEmpty(tendn))
            {
                ViewData["loi2"] = "Phải nhập tên đăng nhập";

            }
            else if (string.IsNullOrEmpty(matkhau))
            {
                ViewData["loi3"] = "Phải nhập mật khẩu";
            }
            else if (string.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["loi4"] = "Phải nhập lại mật khẩu";
            }
            if (string.IsNullOrEmpty(diachi))
            {
                ViewData["loi5"] = "Địa chỉ không được bỏ trống";
            }
            if (string.IsNullOrEmpty(email))
            {
                ViewData["loi6"] = "Email không được bỏ trống";
            }
            if (string.IsNullOrEmpty(dienthoai))
            {
                ViewData["loi7"] = "Phải nhập điện thoại";
            }
            else
            {
                kh.HoTen = hoten;
                kh.TaiKhoan = tendn;
                kh.MatKhau = matkhau;
                kh.Email = email;
                kh.DiaChiKH = diachi;
                kh.DienThoaiKH = dienthoai;
                kh.NgaySinh = DateTime.Parse(ngaysinh);
                data.KhachHangs.InsertOnSubmit(kh);
                data.SubmitChanges();
                return RedirectToAction("DangNhap");
            }
            return this.DangKy();
        }
        public ActionResult DangNhap(FormCollection collection)
        {
            var tendn = collection["TenDN"];
            var matkhau = collection["MatKhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["loi1"] = "Phải nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["loi2"] = "Phải nhập mật khẩu";
            }
            else
            {
                KhachHang kh = data.KhachHangs.SingleOrDefault(n => n.TaiKhoan == tendn && n.MatKhau == matkhau);
                if (kh != null)
                {
                    Session["TaiKhoan"] = kh;
                    return RedirectToAction("Index", "Home");
                }
                else
                    ViewBag.Thongbao = "TÊN ĐĂNG NHẬP HOẶC MẬT KHẨU KHÔNG ĐÚNG";
            }
            return View();
        }
        //Đăng xuất
        public ActionResult Logout()
        {
            Session["TaiKhoan"] = null;
            return RedirectToAction("Index", "Home");
        }

        
    }
}

Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DOANLTW.Models;
using PagedList;
using PagedList.Mvc;
namespace DOANLTW.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        WEBTHUCANNHANHDataContext data = new WEBTHUCANNHANHDataContext();
        private List<MonAn> LayMonAn(int count)
        {
            return data.MonAns.OrderBy(a => a.MaMon).Take(count).ToList();
        }
        public ActionResult Index(int ? page)
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            var monan = LayMonAn(20);
            return View(monan.ToPagedList(pageNum,pageSize));
        }
        public ActionResult ThucDon()
        {
            var thucdon = from td in data.Loais select td;
            return PartialView(thucdon);        

        }
        public ActionResult MATheothucdon(int id)
        {
            var monan = from ma in data.MonAns where ma.MaLoai == id select ma;
            return View(monan);
        }
        public ActionResult Details(int id)
        {
            var monan = from ma in data.MonAns where ma.MaMon == id select ma;
            return View(monan.Single());
        }
    }
}

Views/Shared/_Layout.cshtml
@using DOANLTW.Models;
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Trang chủ</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="/Assets/Client/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/style.css" type="text/css">
   
    <style>
        
        .header__top__right__auth:hover .submenu {
            display: block;
        }

     
        .header__top__right__auth .submenu {
            display: none; 
            position: absolute; 
            background-color: #f9f9f9; 
            min-width: 160px; 
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 1; 
        }

            
            .header__top__right__auth .submenu li {
                color: black; 
                padding: 12px 16px; 
                text-decoration: none; 
                display: block;
            }


                .header__top__right__auth .submenu li:hover {
                    background-color: #e2e2e2;
                }

    </style>
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <!-- Humberger End -->
    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="https://www.facebook.com/narizmusicrl/"><i class="fa fa-facebook"></i></a>
                                <a href="https://twitter.com/GHRWX1"><i class="fa fa-twitter"></i></a>
                            </div>
                            <div class="header__top__right__language">
                                <img src="img/language.png" alt="">
                                <div>Tiếng Việt</div>
                                <span class="arrow_carrot-down"></span>
                                <ul>
                                    <li><a href="#">Tiếng Việt</a></li>
                                    <li><a href="#">Tiếng Anh</a></li>
                                </ul>
                            </div>
                            <div class="header__top__right__auth">
                                @if (Session["TaiKhoan"] != null)
                                {
                                    var taiKhoan = (KhachHang)Session["TaiKhoan"];
                                    <div class="dropdown">
                                        <i class="fa fa-user"></i>@taiKhoan.TaiKhoan
                                        <span class="arrow_carrot-down"></span>
                                        <ul class="submenu">
                                            <li><a href="@Url.Action("Logout", "NguoiDung")">Đăng xuất</a></li>
                                        </ul>
                                    </div>
                                }
                                else
                                {
                                    <a href="@Url.Action("DangNhap", "NguoiDung")"><i class="fa fa-user"></i>Đăng nhập</a>
                                }
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="@Url.Action("Index","Home")"><img src="~/Assets/Images/Logo.jpg" alt="" style="height:50px;width:119px"></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="@Url.Action("Index","Home")">Trang chủ</a></li>
                            <li><a href="@Url.Action("Index","Shop")">Thực đơn</a></li>
                            <li><a href="@Url.Action("Index","Contact")">Liên hệ</a></li>
                            <li>
                                <a href="#">Tài khoản</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="@Url.Action("DangKy","NguoiDung")">Đăng ký</a></li>
                                    <li><a href="@Url.Action("DangNhap","NguoiDung")">Đăng nhập</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    @Html.Action("GioHangPartial", "GioHang")
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->
    <!-- Hero Section Begin -->
    @RenderBody()
    <!-- Footer Section Begin -->
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="@Url.Action("Index","Home")"><img src="~/Assets/Images/Logo.jpg" alt="" style="height:50px;width:119px"></a>
                        </div>
                        <ul>
                            <li>Địa chỉ:140 Lê Trọng Tấn, Phường Tây Thạnh , Tân Phú, TPHCM</li>
                            <li>Điện thoại: 0912 387 121</li>
                            <li>Email: minhtri051003@gmail.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Liên kết</h6>
                        <ul>
                            <li><a href="#">Về chúng tôi</a></li>
                            <li><a href="#">Về Nariz fastfood</a></li>
                            <li><a href="#">Đặt món tiện lợi</a></li>
                            <li><a href="#">Thông tin giao hàng</a></li>
                            <li><a href="#">Chính sách bảo mật</a></li>
                            <li><a href="#">Điều khoản</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Sứ mệnh</a></li>
                            <li><a href="#">Dịch vụ</a></li>
                            <li><a href="#">Món ăn</a></li>
                            <li><a href="#">Liên hệ</a></li>
                            <li><a href="#">Sự đổi mới</a></li>
                            <li><a href="#">Chứng thực</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Cập nhật thông tin mới nhất về Nariz fastfood</h6>
                        <p>Nhận thông tin mới nhất qua email về cửa hàng và những ưu đãi đặc biệt.</p>
                        <form action="#">
                            <input type="text" placeholder="Điền email vào đây">
                            <button type="submit" class="site-btn">Đăng ký</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="http://www.facebook.com/narizmusicrl"><i class="fa fa-facebook"></i></a>
                            <a href="http://www.instagram.com/narizmusic"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    <script src="/Assets/Client/js/jquery-3.3.1.min.js"></script>
    <script src="/Assets/Client/js/bootstrap.min.js"></script>
    <script src="/Assets/Client/js/jquery.nice-select.min.js"></script>
    <script src="/Assets/Client/js/jquery-ui.min.js"></script>
    <script src="/Assets/Client/js/jquery.slicknav.js"></script>
    <script src="/Assets/Client/js/mixitup.min.js"></script>
    <script src="/Assets/Client/js/owl.carousel.min.js"></script>
    <script src="/Assets/Client/js/main.js"></script>

   

</body>

</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Trang chủ</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="/Assets/Client/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="/Assets/Client/css/style.css" type="text/css">

</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <!-- Header Section Begin -->
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="@Url.Action("Index","Home")"><img src="~/Assets/Images/Logo.jpg" alt="" style="height:50px;width:119px"></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="@Url.Action("DonDatHang","Admin")">Đơn hàng</a></li>
                            <li><a href="@Url.Action("Loai","Admin")">Loại món</a></li>
                            <li><a href="@Url.Action("MonAn","Admin")">Món ăn</a></li>
                            <li><a href="@Url.Action("KhachHang","Admin")">Khách hàng</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->
    <!-- Hero Section Begin -->
    @RenderBody()
    <!-- Js Plugins -->
    <script src="/Assets/Client/js/jquery-3.3.1.min.js"></script>
    <script src="/Assets/Client/js/bootstrap.min.js"></script>
    <script src="/Assets/Client/js/jquery.nice-select.min.js"></script>
    <script src="/Assets/Client/js/jquery-ui.min.js"></script>
    <script src="/Assets/Client/js/jquery.slicknav.js"></script>
    <script src="/Assets/Client/js/mixitup.min.js"></script>
    <script src="/Assets/Client/js/owl.carousel.min.js"></script>
    <script src="/Assets/Client/js/main.js"></script>
</body>
</html>